# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Go build

on:  
  pull_request:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            go-version: [ '1.21.1' ]
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
          go-version: ${{ matrix.go-version }}

    - name: display version
      run: |
        go version
        psql --version
    - name: Setup dependencies
      run: go mod download

    - name: Integration Test
      run: |
        
        cd ./test
        go test -run TestHealthTestSuite
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_NAME: postgres

    - name: Build Go artifact
      run: |
          go build 
          ls -l

    - name: Set up Packer
      run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install packer
          packer version

    - name: Check Packer Formatting
      run: |
          packer fmt -check -diff packer.pkr.hcl

    - name: Initialize Packer and install dependencies
      run: packer init packer.pkr.hcl
    
    - name: Validate Packer Configuration
      run: |
          packer validate packer.pkr.hcl